# docker-compose.yml
version: '3'

services:
  serving:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
    image: ift6758/serving:model-serving
    ports:
      - 8890:8890
    environment:
      - COMET_API_KEY=${COMET_API_KEY}
###### Uncomment below when you're ready to add the final notebook container to your docker compose
  streamlit:
    build:
      context: ./
      dockerfile: ./Dockerfile.streamlit
    image: ift6758/streamlit:model-streamlit
    ports:
      - 8000:8000
    environment:
      - COMET_API_KEY=${COMET_API_KEY}
      
